version: '2'
services:
  web:
    build: .
    command: mix run --no-halt
    ports:
      - 8000:8000
    volumes:
      - ./:/fiesp
    links:
      - rethinkdb
    depends_on:
      - rethinkdb
  rethinkdb:
    image: rethinkdb
    ports:
      - 8080:8080
