version: '2'
services:
  web:
    image: gabrielcorado/hackathon-fiesp
    command: mix run --no-halt
    ports:
      - 80:80
    links:
      - rethinkdb
    depends_on:
      - rethinkdb
  rethinkdb:
    image: rethinkdb
